### ISSUE TITLE
Question: Untis version

### ISSUE THREAD

**Issue by M123-dev** [AppleFoxUser42/UntisTHMScraper#3]
Hello there, first of all great project. However, it looks like the THM has switched to a different system.

I'm working on a similar project for my school, do you happen to remember which Untis version was used and how the authentication worked?

**Comment by Ozymandias42** [comment]
> Hello there, first of all great project. However, it looks like the THM has switched to a different system.
> 
> I'm working on a similar project for my school, do you happen to remember which Untis version was used and how the authentication worked?

Hi and thanks for commenting this old project of mine.
Unfortunately I don't. I never actually looked it up in the first place and only programmed this as both an exercise for myself and because I was annoyed at not having an option to view multiple schedules at once in one window.

From what I know however is that THM is in fact still using Untis to do their planning. They merely switched the frontend to present the plans created with Untis. My program here was tailored towards the old frontend.

**Comment by M123-dev** [comment]
Thanks for your reply @Ozymandias42, no problem and good to know that this project doesn't work anymore. However, in the meantime I have decided to instead build my own little scraper instead anyways. But thanks for answering my question.
